#include "shapes/rectangle.h"
#include "shapes/circle.h"
#include "shapes/cube.h"
#include "shapes/sphere.h"
#include "shapes/icosahedron.h"
#include "shapes/icosphere.h"
#include "shapes/superquadric.h"
#include "shapes/cylinder.h"
