#!/usr/bin/env python

import sys
import numpy as np
import nrrd

if(len(sys.argv) <= 1):
	print("Input NumPy file to convert as an argument")
	exit(0)

in_file = sys.argv[1]
if(len(sys.argv) == 2):
	out_file = sys.argv[1] + ".nrrd"
else:
	out_file = sys.argv[2]


A = np.load(in_file)
nrrd.write(out_file, A)